- name: create group
  group: name=www

- name: create user
  user: name=httpd groups=www state=present

- name: create group
  group: name=kusanagi

- name: create user
  user: name=kusanagi groups=kusanagi,www state=present

- name: chmod
  file: path=/home/kusanagi mode=0701

- name: ensure a list of packages installed
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - git
    - wget
    - expect
    - php-cli
    - kusanagi
    - kusanagi-apr
    - kusanagi-apr-devel
    - kusanagi-apr-util
    - kusanagi-apr-util-devel
    - kusanagi-hhvm
    - kusanagi-httpd
    - kusanagi-libzip
    - kusanagi-mozjpeg
    - kusanagi-nghttp2
    - kusanagi-nginx
    - kusanagi-openssl
    - kusanagi-php7
    - kusanagi-ruby2.4
    - kusanagi-wp
    - kusanagi-wp-cli

- name: git clone certbot
  git:
    repo: https://github.com/certbot/certbot.git
    dest: /usr/local/certbot

- name: check initializer
  stat:
    path: "/usr/local/sbin/setup_kusanagi.sh"
  register: stat_setup_kusanagi

- name: download initializer
  get_url: url=https://raw.githubusercontent.com/ConoHa/startupscripts/master/scripts/setup_kusanagi.sh dest=/usr/local/sbin/setup_kusanagi.sh
  when: not stat_setup_kusanagi.stat.exists

- name: execute initializer
  shell: "/bin/bash /usr/local/sbin/setup_kusanagi.sh"
  when: not stat_setup_kusanagi.stat.exists
