- name: ensure a list of packages installed
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - MariaDB-client
    - MariaDB-server
    - MariaDB-devel
    - MariaDB-common
    - MariaDB-shared

- name: enable and restart mariadb.service
  systemd:
    name: mariadb.service
    state: restarted
    daemon_reload: yes
    enabled: yes
  become: yes
