---
- name: check repo file
  stat:
    path: "/etc/yum.repos.d/mariadb.repo"
  register: stat_mariadb_repo

- name: download installer
  get_url: url=https://downloads.mariadb.com/MariaDB/mariadb_repo_setup dest=/tmp/mariadb_repo_setup
  when: not stat_mariadb_repo.stat.exists

- name: install mariadb repo
  shell: "/bin/bash /tmp/mariadb_repo_setup --mariadb-server-version=mariadb-10.1"
  when: not stat_mariadb_repo.stat.exists

- name: remove installer
  file: path=/tmp/mariadb_repo_setup state=absent
  when: not stat_mariadb_repo.stat.exists
